### ISSUE TITLE
ETL

### ISSUE THREAD

**Issue by trentgoing** [EddySantos07/ETL-test2#2]
https://github.com/EddySantos07/ETL-test2/blob/7a6da7b28be45bf01dbe894e75fe4cc7a1929b14/FSquestions.js#L1

These streams seem like the start of the whole ETL process.  However, it's not clear what the other steps were or how it could be recreated.  Try to add code that outline the remaining steps you took in your repository.

**Comment by EddySantos07** [comment]
I accidentally took out the whole ETL proccess and now my new System Design modularized and less memory leak prone is at - https://github.com/EddySantos07/System-Design
